apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo
  namespace: benchmark
spec:
  description: "Just hello world task"
  params: []
  results: []
  steps:
    - name: echo
      image: registry.redhat.io/ubi8/ubi-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      script: |
        #!/usr/bin/env bash
        echo "Hello World from Git Resolver Performance Benchmark Test resolved by git"