
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo
  namespace: utils
spec:
  description: "Just hello world task"
  params: []
  results: []
  steps:
    
    - name: echo1
      image: registry.redhat.io/ubi8/ubi-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Hello World from Git Resolver Performance Benchmark Test 1 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 2 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 3 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 4 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 5 from Task"

    
    - name: echo2
      image: registry.redhat.io/ubi8/ubi-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Hello World from Git Resolver Performance Benchmark Test 6 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 7 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 8 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 9 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 10 from Task"

    
    - name: echo3
      image: registry.redhat.io/ubi8/ubi-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Hello World from Git Resolver Performance Benchmark Test 11 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 12 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 13 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 14 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 15 from Task"

    
    - name: echo4
      image: registry.redhat.io/ubi8/ubi-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Hello World from Git Resolver Performance Benchmark Test 16 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 17 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 18 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 19 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 20 from Task"

    
    - name: echo5
      image: registry.redhat.io/ubi8/ubi-minimal@sha256:574f201d7ed185a9932c91cef5d397f5298dff9df08bc2ebb266c6d1e6284cd1
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        echo "Hello World from Git Resolver Performance Benchmark Test 21 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 22 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 23 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 24 from Task"
        echo "Hello World from Git Resolver Performance Benchmark Test 25 from Task"
